DROP TABLE IF EXISTS Telefonos;
DROP TABLE IF EXISTS Personas;

CREATE TABLE Personas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  direccion VARCHAR(200)
);

CREATE TABLE Telefonos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  personaId INT NOT NULL,
  telefono VARCHAR(20) NOT NULL,
  CONSTRAINT fk_persona
    FOREIGN KEY (personaId) REFERENCES Personas(id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);
